import k from "./public/modules/kaboom.js";
import menu from "./public/scene/menu.js";
import Game from "./public/scene/game.js";
import playerSelectMenu from "./public/scene/playerSelectMenu.js";
import { loadAssets } from "./public/chars/loadAssets.js";
import { story } from "./public/scene/story.js";
import { loading } from "./public/scene/loading.js";
import { pvp } from "./public/scene/pvp.js";
loading();
loadAssets();
menu.loadAsset();
menu.introScene();
menu.menuScene();
playerSelectMenu();
Game();
pvp();
story();
go("intro");
